#!/bin/bash
# This hook is sourced after every virtualenv is activated.

OLDCURDIR=$PWD


[[ "$OLDPS1" != "$PS1" ]] &&
    OLDPS1=$PS1

PGVER='9.4'
V="$HOME/.virtualenvs"

export THIS=$( basename $VIRTUAL_ENV )
export H=$HOME/work/git/${THIS}

[[ ! -f $HOME/work/git/$THIS/.nopg ]] &&
if [[ -f $V/last_venv ]];
then
    [[ -n "$THAT" ]]  && export THAT=$( cat $V/last_venv ) 
    if [[ "$THIS" != "$THAT" ]];
    then
        if  [[ -f $V/PG/${THAT}/postmaster.pid ]];
        then
            echo "stopping postgres instance: $THAT"
            kill -2 $( $V/PG/${THAT}/postmaster.pid )
        fi
        echo -n $THIS > $V/last_venv 
    else
        export THAT=$THIS
    fi
    export THAT=$THIS
else
    echo -n $THIS > $V/last_venv
fi &&


export PGDATA="$V/PG/${THIS}" &&
export PGHOST="$V/PG/${THIS}" &&

if [[ -d $PGDATA ]];
then
    if [[ ! -f $PGDATA/postmaster.pid ]];
    then
        echo "starting postgres instance: $THIS"
        postgres -D $PGDATA -k $PGDATA >& $PGDATA/postgres.log &
    else
        if ! pgrunning;
        then
            rm -f $PGDATA/postmaster.pid
            nohup postgres -k $PGDATA -D $PGDATA >& $PGDATA/postgres.log &
        fi
    fi
else
    initdb $PGDATA >& $PGDATA/postgres.log
    postgres -k $PGDATA -D $PGDATA >& $PGDATA/postgres.log &
    sleep 5
    createuser  revsysuser &&
    createdb  -O revsysuser django &&
    createdb  $( whoami )
fi


[[ -f $V/set_prompt ]] && . $V/set_prompt

[[ ! -d $H ]] && mkdir -p $H

#cd $H
